# Generated by Django 3.2.14 on 2022-08-26 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIJobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('url', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('api_method', models.TextField(default='get')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('group', models.TextField(default='bkc_regression')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(default='', unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('auto_debug', models.BooleanField(default=False)),
                ('pause_jobs', models.BooleanField(default=False)),
                ('stop_jobs', models.BooleanField(default=False)),
                ('saved_job_limit', models.IntegerField(default=20)),
                ('timeout_limit', models.IntegerField(default=300)),
                ('max_debug_attempts', models.IntegerField(default=1)),
                ('current_debug_attempts', models.IntegerField(default=0)),
                ('kwargs', models.TextField(default='')),
                ('last_active_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active_debug_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='APIJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('job_type', models.TextField(default='normal')),
                ('iterations', models.IntegerField(default=1)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_count', models.IntegerField(default=0)),
                ('kwargs', models.TextField(default='')),
                ('apijobtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apijobtemplate')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
        ),
    ]
